export const AccessKeys = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_REGISTER: "USER_REGISTER",
  USER_FORGOT_PASSWORD: "USER_FORGOT_PASSWORD",
  USER_REFRESH_TOKEN: "USER_REFRESH_TOKEN",
};
