export const BookKeys = {
  GET_LIST_SEARCH_BOOK: "GET_LIST_SEARCH_BOOK",
  GET_BOOK_PUBLISHS: "GET_BOOK_PUBLISHS",
  GET_LIST_NEWEST_BOOK: "GET_LIST_NEWEST_BOOK",
  GET_LIST_RECOMMEND_BOOK: "GET_LIST_RECOMMEND_BOOK",
  GET_LIST_SORT_READS: "GET_LIST_SORT_READS",
  GET_BOOKS_BY_CATEGORY_ID: "GET_BOOKS_BY_CATEGORY_ID",
  GET_ALL_BOOK_NOT_DELETED_BY_ADMIN: "GET_ALL_BOOK_NOT_DELETED_BY_ADMIN",
  FIND_BOOK_BY_TEXT_SEARCH: "FIND_BOOK_BY_TEXT_SEARCH",
};
