export const BookKeys = {
  GET_BOOK_PUBLISHS: "GET_BOOK_PUBLISHS",
  GET_LIST_NEWEST_BOOK: "GET_LIST_NEWEST_BOOK",
  GET_LIST_RECOMMEND_BOOK: "GET_LIST_RECOMMEND_BOOK",
  GET_LIST_SORT_READS: "GET_LIST_SORT_READS",
  GET_BOOKS_BY_CATEGORY_ID: "GET_BOOKS_BY_CATEGORY_ID",
};
