export const CvKeys = {
  GET_ALL_CV_BY_ADMIN: "GET_ALL_CV_BY_ADMIN",
  GET_CV_BY_ID: "GET_CV_BY_ID",
  GET_CVS_BY_USER_ID: "GET_CVS_BY_USER_ID",
  GET_CV_BY_ID_AND_USER_ID: "GET_CV_BY_ID_AND_USER_ID",
};
