
export const noteKeys = {
    GET_ALL_NOTE_BY_USERID: 'GET_ALL_NOTE_BY_USERID',
};

export const NoteKeys = {

 
  GET_NHUNG_NOTE_HOM_NAY: "GET_NHUNG_NOTE_HOM_NAY",
  GET_NOTE_CHINH_CUA_USER: "GET_NOTE_CHINH_CUA_USER",
};

