export const NoteKeys = {
  GET_ALL_NOTE_BY_USERID: "GET_ALL_NOTE_BY_USERID",
  GET_NHUNG_NOTE_HOM_NAY: "GET_NHUNG_NOTE_HOM_NAY",
  GET_NOTE_CHINH_CUA_USER: "GET_NOTE_CHINH_CUA_USER",
  GET_NOTE_CHI_TIET_BANG_ID: "GET_NOTE_CHI_TIET_BANG_ID",
  GET_ALL_NOTE_BY_ADMIN: "GET_ALL_NOTE_BY_ADMIN",
  GET_NOTE_DELETED_BY_USERID: "GET_NOTE_DELETED_BY_USERID",
};
