export const UserKeys = {
  GET_USER_BOOKS_READING: "GET_USER_BOOKS_READING",
  GET_USER_BOOKS_READED: "GET_USER_BOOKS_READED",
  GET_STUDENT_INFORMATION_BY_USER_ID: "GET_STUDENT_INFORMATION_BY_USER_ID",
};
